#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 22 21:54:14 2018

@author: alexanderosorio
"""

from PIL import Image 
from pylab import *

def histeq(im,nbr_bins=256):
    imhist,bins = histogram(im.flatten(),nbr_bins,normed=True) 
    cdf = imhist.cumsum() # cumulative distribution function 
    cdf = 255 * cdf / cdf[-1] # normalize
# use linear interpolation of cdf to find new pixel values
    im2 = interp(im.flatten(),bins[:-1],cdf)
    return im2.reshape(im.shape), cdf

# read image to array
im = array(Image.open('imagen2.jpg').convert('L'))
# create a new figure
figure()
# don't use colors
gray()
# show contours with origin upper left corner
contour(im, origin='image') 
axis('equal')
axis('off')
figure() 
hist(im.flatten(),128)
im3 = array(Image.open('imagen2.jpg').convert('L'))
im2,cdf = histeq(im3)




